"""create series and observations

Revision ID: 4e6342c11a19
Revises: 
Create Date: 2026-06-26 01:05:11.643854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e6342c11a19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('xcat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_series_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('regime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vintage_capable', sa.Boolean(), nullable=False),
    sa.Column('commercial_ok', sa.Boolean(), nullable=False),
    sa.Column('attribution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_table('observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('vintage_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.series_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_series_id'), 'observation', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observation_series_id'), table_name='observation')
    op.drop_table('observation')
    op.drop_table('series')
    # ### end Alembic commands ###
